version: "3.9"
services:
  backend:
    build: .
    command: yarn server:dev
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
  frontend:
    build: .
    command: yarn dev --host 0.0.0.0
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
